import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../shared/styles/globals.css";
import { cn } from "@/features/shadcn/lib/utils";
import { ThemesProvider } from "@/features/themes/providers/ThemeProvider";
import { TooltipProvider } from "@/features/shadcn/ui/tooltip";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn("flex w-screen min-h-screen antialiased", "font-sans", inter.variable)}
			suppressHydrationWarning
		>
			<body className="flex flex-col grow w-full">
				<TooltipProvider>
					<ThemesProvider>
						<main className="flex grow w-full **:w-full">{children}</main>
					</ThemesProvider>
				</TooltipProvider>
			</body>
		</html>
	);
}
